name: Greeting on variable day

on:
  push

env:
  var1: Monday from flow

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      var1: monday from job
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$var1"
        #env:
          #var1: monday from step
